config/routes.rb
Depot::Application.routes.draw do
  
    get 'admin' => 'admin#index'
   
    controller :sessions do
      get 'login' => :new
      post 'login' => :create 
      delete 'logout' => :destroy
    end
  
    resources :users
  
    resources :store
  
    resources :carts do
      resources :line_items
    end
  
    resources :orders do
      resources :line_items
    end
    
    resources :orders do
      resources :payment_types
    end
  
    resources :payment_types do
      resources :orders
    end
  
    resources :products do
      resources :line_items
    end
  
    resource :products do
      resource :line_items do
        resource :orders do
          resource :payment_types  
        end
      end
    end 
  
    resources :line_items
  
    resources :carts
  
    resources :products
  
    resources :orders
  
    resources :products do
      get :who_bought
      get "products/index"
    end
  
    resources :payment_types
    
  
    match ':controller(/:action(/:id(.:format)))', :via => [:get, :post, :delete, :patch, :put]
  
  
  
  
  
  
  
  
    
  
  
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :line_items, :dependent => :destroy
  has_many :products, :through => :line_items
  belongs_to :payment_types
  
  PAYMENT_TYPES = [ 1, 2, 3, 4, 5 ]
  
  validates :name, :address, :email, :payment_type_id, :presence => true 
  validates :payment_type_id, :inclusion => PAYMENT_TYPES
  scope :sorted, lambda { order("orders.id ASC")}
 
  
  def add_line_items_from_cart(current_cart, order_id)
    
    for items in LineItem.where(:cart_id => current_cart.id)
      items.order_id = order_id
      items.update_attributes(:id => items.id)
    end   
    
  end
  
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  skip_before_filter :authorize, :only => [:new, :create]
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  sleep 1
  
  # GET /orders
  # GET /orders.json
  def index
#    @orders = Order.all
    @orders = Order.paginate :page => params[:page], :order => 'created_at desc', :per_page => 10
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @order = Order.find(params[:id])
    @product = Product.order(params[:id])
    @cart = Cart.find_by_id(session[:cart_id])
    @line_item = LineItem.where(:cart_id => session[:cart_id])

    respond_to do |format|
      format.html
      format.atom
      format.xml { render :xml => @product.to_xml(:include => :orders)  }
      format.json
    end    
    
  end

  # GET /orders/new
  def new
    
    @cart = current_cart
    if @cart.line_items.empty?
      flash[:notice] = "Your cart is empty"
      redirect_to(controller: 'store', action: 'index' )
      return
    end

    @order = Order.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.js   # new.js.erb 
      
#      format.json { render controller: 'store', action: 'index', status: :created, location: @order }
    end     
  end

  # GET /orders/1/edit
  def edit
    @order = Order.find_by_id(params[:id])
    
    @cart = Cart.find_by_id(session[:cart_id])
    @line_item = LineItem.where(:cart_id => session[:cart_id])
  end

  # POST /orders
  # POST /orders.json
  def create
    
    @order = Order.new(order_params)
    
    respond_to do |format|
      if @order.save
        
        @order.add_line_items_from_cart(current_cart, @order.id)

        Cart.destroy(session[:cart_id])
        session[:cart_id] = nil
        
        Notifier.order_received(@order).deliver
         
        flash[:notice] =  'Thank you for your order.' 
            
        format.html { redirect_to(controller: 'store', action: 'index') }
#            format.html { render action: 'show', :id => @order.id ,notice: 'Verify your information' }
        format.json { render controller: 'order', action: 'show', status: :created, location: @order }
      else
        flash[:notice] =  'Cart is empty.'
        format.html { redirect_to(controller: 'store', action: 'index') }
#            format.html { redirect_to(controller: 'store', action: 'index' , notice: 'Cart is empty') }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
      
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    @order = Order.find(params[:id])
    
    respond_to do |format|
      if @order.update(order_params)
#      if @order.update_attributes(params[:order])
        
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order = Order.find(params[:id])

    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:name, :address, :email, :payment_type_id)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_checkout_button.html.erb
<div id="side-buttons">
	<%= button_to "Checkout", new_order_url, :method=> :get, :remote => true, :id => 'button_id', :disabled => true %>
	<%= button_to 'Empty cart', cart_path(:id => @cart.id), :method => :delete, data: { confirm: 'Are you sure?' }, :remote => true, :disabled => true %>
</div>

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, t('order.name') %><br>
    <%= f.text_field :name, :size => 40 %>
  </div>
  <div class="field">
    <%= f.label :address, t('order.address') %><br>
    <%= f.text_area :address, :rows => 3, :cols => 40 %>
  </div>
  <div class="field">
    <%= f.label :email, t('order.email') %><br>
    <%= f.text_field :email, :size => 40 %>
  </div>
  
  <div class="field">
    <%= f.label :payment_type_id, t('order.paywith') %><br>
    <%= f.collection_select :payment_type_id, PaymentType.all, :id, :name, {:prompt => t('order.select-method') }
    
		%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/_new2014.html.erb
<div class="depot_form">
  <fieldset>
     <legend>Please Enter Your Details</legend> 
     <%= render 'form' %>
  </fieldset>
</div>
<%= link_to 'Back', orders_path %>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<h1>Listing orders</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Email</th>
      <th>Pay type</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.name %></td>
        <td><%= order.address %></td>
        <td><%= order.email %></td>
        <% payment = PaymentType.find_by_id(order.payment_type_id) %>
        <td><%= payment.name %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>
<p><%= will_paginate @orders %></p>

app/views/orders/new.html.erb
<div class="depot_form">
  <fieldset>
<legend> 
	<%= t('order.title')  %>
</legend> <%= render 'form' %>
  </fieldset>
</div>
<%= link_to 'Back', orders_path %>

app/views/orders/new.js.erb
/**
 * @author Edwin Caro
 */
$()
$('#side-buttons').html("<%= j (render('checkout_button')) %>");
$('#main').html("<%= j (render('new2014')) %>").slidedown( "slow" );

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @order.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @order.address %>
</p>

<p>
  <strong>Email:</strong>
  <%= @order.email %>
</p>

<p>
  <strong>Pay type:</strong>
  <% payment = PaymentType.find_by_id(@order.payment_type_id) %>
  <%= payment.name %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>