config/routes.rb
Depot::Application.routes.draw do
  
    get 'admin' => 'admin#index'
   
    controller :sessions do
      get 'login' => :new
      post 'login' => :create 
      delete 'logout' => :destroy
    end
  
    resources :users
  
    resources :store
  
    resources :carts do
      resources :line_items
    end
  
    resources :orders do
      resources :line_items
    end
    
    resources :orders do
      resources :payment_types
    end
  
    resources :payment_types do
      resources :orders
    end
  
    resources :products do
      resources :line_items
    end
  
    resource :products do
      resource :line_items do
        resource :orders do
          resource :payment_types  
        end
      end
    end 
  
    resources :line_items
  
    resources :carts
  
    resources :products
  
    resources :orders
  
    resources :products do
      get :who_bought
      get "products/index"
    end
  
    resources :payment_types
    
  
    match ':controller(/:action(/:id(.:format)))', :via => [:get, :post, :delete, :patch, :put]
  
  
  
  
  
  
  
  
    
  
  
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :cart

  def total_price
    total = price * quantity
    total
  end 
  
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  skip_before_filter :authorize, :only => :create
  before_action :set_line_item, only: [:verificacion, :show, :edit, :update, :destroy]
  
  layout "application"

  # GET /line_items
  # GET /line_items.json
  def index 
     
    @line_items = LineItem.all
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
    
  end

  # GET /line_items/new
  def new
    
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
   
  end
 
 
  # POST /line_items
  # POST /line_items.json
  def create
  # Sustituida por la linea despues de product = Pro...  
  #  @line_item = LineItem.new(line_item_params)
  
    @cart = current_cart   
    
    product = Product.find_by_id(params[:product_id].to_i)    
    
    @line_item = @cart.add_product(product, @cart)
    
    session[:counter] = 0
    @current_item = @line_item

    session[:current_item] = @current_item.id
           
    respond_to do |format|
      if @line_item.save        
        format.html { redirect_to :back }
        format.js   { @current_item }
        format.json { render action: 'show', status: :created, location: @line_item }
      else
        format.html { render action: 'new' }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    
    @cart = current_cart  
       
#    product = Product.find_by_id(@line_item.product_id)    
 
    @line_item = nil
    @line_item = LineItem.find_by_id(params[:id].to_i)
#    @line_item = @cart.upd_product(product, @cart)
            
      session[:counter] = 0
      @line_item.quantity = @line_item.quantity - 1
      @current_item = nil
      @current_item = @line_item
      
      session[:current_item] = @current_item.id    
      
      respond_to do |format| 
      
        if @line_item.update_attributes(:id => params[:id].to_i)
          
           if @line_item.quantity < 1
             delete_line_item(@line_item.id)
           end
           
           format.html { redirect_to store_path }
           format.js   { @current_item }
           format.json { head :no_content }
        else
            
           format.html { render action: 'edit' }
           format.js   { @current_item }
           format.json { render json: @line_item.errors, status: :unprocessable_entity }
        end
      end     
  end
   
  # DELETE /line_items/1
  # DELETE /line_items/1.json
  
  def destroy
    
    @cart = current_cart
    @line_item = LineItem.find(params[:id])
    
    @line_item.destroy
        
    respond_to do |format|            
       
      format.html { redirect_to store_path  }
      format.js { @cart }
      format.json { head :no_content }
    end
   
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params      
      params.require(:line_item).permit(:product_id, :cart_id, :quantity, :price)
    end
   
    def delete_line_item(id)
      
      line_item = LineItem.find(id)
      line_item.destroy
        
    end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.erb
<%= form_for(@line_item) do |f| %>
  <% if @line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% @line_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.number_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :cart_id %><br>
    <%= f.number_field :cart_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/line_items/_helper_goback.html.erb
<%= redirect_to( stores_path ) %>

app/views/line_items/_line_items.html.erb
<% if session[:current_item]  %>
<%    @current_item = LineItem.find_by_id( session[:current_item] ) %>
<% end %>

<% if item == @current_item %>
	<tr id="current_item">	
<% else %>
	<tr>
<% end %>

		<td><%= item.quantity %>&times;</td>
		<td><%= item.product.title %></td>
		<td class="item_price"><%= number_to_currency( item.total_price ) %></td>
	
		<td><%= link_to t('cart.del'), line_item_path(:id => item.id), 
	          method: :delete, data: { confirm: t('cart.confirmation') }, :class => 'delete_book', :remote => true %></td>

     	<td><%= link_to t('cart.min'), line_item_path(:id => item.id), method: :patch, :class => 'modify_book',:remote => true %></td>
	     	     
	</tr>
	

app/views/line_items/_line_items.text.erb
<%= sprintf("%2d x %s", line_item.quantity,truncate(line_item.product.title, :length => 50)) %>

app/views/line_items/create.js.erb
/**
 * @author Edwin Caro
 */

//#START_HIGHLIGHT
$('#notice').hide();

//#END_HIGHLIGHT
if ($('#cart tr').length == 1) { $('#cart').show('blind', 1000); }

$('#cart').html("<%= escape_javascript(render(@cart)) %>");

$('#current_item').css({'background-color':'#88ff99'}).
  animate({'background-color':'#114411'}, 1000);

app/views/line_items/destroy.js.erb
/**
 * @author Edwin Caro
 */

$('#cart').html("<%= j (render(@cart)) %>").slidedown( "slow" );

app/views/line_items/edit.html.erb
<h1>Editing line_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<h1>Listing line_items</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Cart</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.product_id %></td>
        <td><%= line_item.cart_id %></td>
        <td><%= link_to 'Show', line_item %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New line_item</h1>

<%= render 'form' %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @line_item.product_id %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @line_item.cart_id %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path(:product_id => @line_item.product_id) %>

app/views/line_items/update.js.erb
/**
 * @author Edwin Caro
 */

//#START_HIGHLIGHT
$('#notice').hide();

//#END_HIGHLIGHT

if ($('#cart tr').length == 1) { $('#cart').show('blind', 1000); }

$('#cart').html("<%= j (render(@cart)) %>").slidedown( "slow" );

$('#current_item').css({'background-color':'#88ff99'}).
  animate({'background-color':'#114411'}, 100);
  